service: tomas37_signals

image: tomycostantino/tomas37_signals

servers:
  web:
    - 128.140.37.238

proxy:
  ssl: true
  host: 37signals.tomascostantino.dev
  app_port: 3000

registry:
  username: tomycostantino
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
  clear:
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "tomas37_signals_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

